variables:
  PROJECT_NAME: 'LeetCode_463_TDD'
before_script:
  - echo "starting build for %PROJECT_NAME%"
  - echo "Restoring NuGet Packages..."
  - nuget restore "%PROJECT_NAME%.sln"
stages:
  - build
  - test
build:
  stage: build
  script:
    - echo "Release build..."
    - msbuild /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet %PROJECT_NAME%.sln
  artifacts:
    untracked: true
test:
  stage: test
  script:
    - echo "starting tests"
    - dir /s /b *.Tests.dll | findstr /r Tests\\*\\bin\\ > testcontainers.txt
    - 'for /f %%f in (testcontainers.txt) do mstest.exe /testcontainer:"%%f"'
  dependencies:
    - build
